services:
  - type: web
    name: opencourseware-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    envVars:
      - key: DATABASE_URL
        value: postgresql+asyncpg://postgres:nfMWCACJCkSCRLgMlDGVSzjCigUIrLHc@tramway.proxy.rlwy.net:11497/railway
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        value: guzeman88@yahoo.com
      - key: ADMIN_PASSWORD
        value: Iamfree2
      - key: DEBUG
        value: "false"
      - key: PORT
        value: "8000"
