import psycopg2, os
conn = psycopg2.connect(os.environ["DATABASE_URL"], sslmode="disable")
cur = conn.cursor()
cur.execute("SELECT source_key, COUNT(*) FROM courses WHERE source_key ILIKE '%nptel%' OR title ILIKE '%nptel%' GROUP BY source_key")
rows = cur.fetchall()
print("By source_key:", rows)
cur.execute("SELECT COUNT(*) FROM courses WHERE source_key ILIKE '%nptel%' OR title ILIKE '%nptel%'")
print("Total (all):", cur.fetchone()[0])
cur.execute("UPDATE courses SET is_published=FALSE WHERE source_key ILIKE '%nptel%'")
print("Unpublished by source_key:", cur.rowcount)
conn.commit()
conn.close()
