"""UC Berkeley Webcasts / YouTube channel scraper."""
from __future__ import annotations

import logging

from slugify import slugify

from scrapers.base import BaseScraper, ScrapedCourse, ScraperResult

logger = logging.getLogger(__name__)

BERKELEY_COURSES = [
    # ── CS Core ──────────────────────────────────────────────────────────────
    {
        "title": "CS 61A: Structure and Interpretation of Computer Programs",
        "instructor": "Brian Harvey",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://archive.org/details/ucberkeley_webcast_itunesu_461214977",
        "youtube_playlist_id": "PLhMnuBfGeCDNgVzLPxF9o5UNKG7LeZyng",
        "level": "undergraduate",
        "year": 2011,
        "subjects": ["Programming", "Computer Science", "SICP"],
    },
    {
        "title": "CS 61B: Data Structures",
        "instructor": "Josh Hug",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://inst.eecs.berkeley.edu/~cs61b/",
        "youtube_playlist_id": "PL8FaHk7qbOD4oAdQOZ765z6aeqyKs2593",
        "level": "undergraduate",
        "year": 2021,
        "semester": "Spring",
        "subjects": ["Data Structures", "Java", "Computer Science"],
    },
    {
        "title": "CS 61C: Great Ideas in Computer Architecture",
        "instructor": "Dan Garcia",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://inst.eecs.berkeley.edu/~cs61c/",
        "youtube_playlist_id": "PLDoI-XvXX0kUoMBIWKGwfAlZmq3K8Q7Gu",
        "level": "undergraduate",
        "year": 2020,
        "semester": "Fall",
        "subjects": ["Computer Architecture", "Computer Science"],
    },
    {
        "title": "CS 70: Discrete Mathematics and Probability Theory",
        "instructor": "Various",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://www.eecs70.org/",
        "youtube_playlist_id": "PLIygTcviGPKDV7TrbTokEDN0haWwiV_xp",
        "level": "undergraduate",
        "year": 2025,
        "semester": "Fall",
        "subjects": ["Discrete Mathematics", "Probability", "Mathematics"],
    },
    {
        "title": "CS 10: The Beauty and Joy of Computing",
        "instructor": "Dan Garcia",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "http://www.infocobuild.com/education/audio-video-courses/computer-science/cs10-spring2015-berkeley.html",
        "level": "undergraduate",
        "year": 2015,
        "semester": "Spring",
        "subjects": ["Computer Science", "Programming", "Introduction"],
    },
    {
        "title": "CS 149: Introduction to Embedded Systems",
        "instructor": "Jonathan Bachrach",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://youtube.com/playlist?list=PLu0nzW8Es1x0RIvuWdw1Diez2Clk8xAX5",
        "youtube_playlist_id": "PLu0nzW8Es1x0RIvuWdw1Diez2Clk8xAX5",
        "level": "undergraduate",
        "year": 2011,
        "semester": "Spring",
        "subjects": ["Embedded Systems", "Computer Architecture", "Computer Science"],
    },
    {
        "title": "CS 152: Computer Architecture and Engineering",
        "instructor": "Various",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://inst.eecs.berkeley.edu/~cs152/",
        "level": "undergraduate",
        "year": 2021,
        "semester": "Spring",
        "subjects": ["Computer Architecture", "Computer Science", "Hardware"],
    },
    {
        "title": "CS 161: Computer Security",
        "instructor": "Various",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://fa23.cs161.org/",
        "youtube_playlist_id": "PLfBkt1-_BHX_VxOWlmstguFxojSN742vz",
        "level": "undergraduate",
        "year": 2023,
        "semester": "Fall",
        "subjects": ["Computer Security", "Cryptography", "Computer Science"],
    },
    {
        "title": "CS 162: Operating Systems and System Programming",
        "instructor": "Ion Stoica",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://inst.eecs.berkeley.edu/~cs162/",
        "youtube_playlist_id": "PLF2K2xZjNEf97A_uBCwEl61sdxWVP7VWC",
        "level": "undergraduate",
        "year": 2020,
        "semester": "Fall",
        "subjects": ["Operating Systems", "Computer Science", "Systems Programming"],
    },
    {
        "title": "CS 164: Programming Languages and Compilers",
        "instructor": "Various",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://inst.eecs.berkeley.edu/~cs164/",
        "youtube_playlist_id": "PLkFD6_40KJIwXguSMHFVuvMkO7FxXTkFC",
        "level": "undergraduate",
        "year": 2021,
        "semester": "Spring",
        "subjects": ["Programming Languages", "Compilers", "Computer Science"],
    },
    {
        "title": "CS 168: The Modern Algorithmic Toolbox",
        "instructor": "Tim Roughgarden",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://fa22.cs168.io/",
        "youtube_playlist_id": "PLIygTcviGPKD4RbcpiXKeyXrIImw-mGd-",
        "level": "undergraduate",
        "year": 2022,
        "semester": "Fall",
        "subjects": ["Algorithms", "Computer Science", "Data Structures"],
    },
    {
        "title": "CS 169: Software Engineering",
        "instructor": "Armando Fox",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://youtube.com/playlist?list=PLkFD6_40KJIxCKgzL0uysjsAtfY3JawLS",
        "youtube_playlist_id": "PLkFD6_40KJIxCKgzL0uysjsAtfY3JawLS",
        "level": "undergraduate",
        "year": 2019,
        "semester": "Fall",
        "subjects": ["Software Engineering", "Computer Science"],
    },
    {
        "title": "CS 170: Efficient Algorithms and Intractable Problems",
        "instructor": "Prasad Raghavendra",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://inst.eecs.berkeley.edu/~cs170/",
        "youtube_playlist_id": "PLIygTcviGPKD7jFi6bSTKH0_c0s-mGCJE",
        "level": "undergraduate",
        "year": 2022,
        "semester": "Fall",
        "subjects": ["Algorithms", "Computer Science"],
    },
    {
        "title": "CS 182/282A: Designing, Visualizing and Understanding Deep Neural Networks",
        "instructor": "Anant Sahai",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://inst.eecs.berkeley.edu/~cs182/",
        "youtube_playlist_id": "PLIygTcviGPKAaj_UAJcazYN4964xZ7Lt1",
        "level": "graduate",
        "year": 2023,
        "semester": "Spring",
        "subjects": ["Deep Learning", "Neural Networks", "Machine Learning"],
    },
    {
        "title": "CS 184/284A: Computer Graphics and Imaging",
        "instructor": "Ren Ng",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://cs184.eecs.berkeley.edu/sp22",
        "youtube_playlist_id": "PLIygTcviGPKABEUa7EJzO8tgYRz120EpP",
        "level": "undergraduate",
        "year": 2022,
        "semester": "Spring",
        "subjects": ["Computer Graphics", "Rendering", "Computer Science"],
    },
    {
        "title": "CS 186: Introduction to Database Systems",
        "instructor": "Various",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "http://www.infocobuild.com/education/audio-video-courses/computer-science/cs186-spring2015-berkeley.html",
        "youtube_playlist_id": "PLYdJCSN-m81bnB9jPwsEGbVZ5Jmn_ck1I",
        "level": "undergraduate",
        "year": 2021,
        "subjects": ["Databases", "Computer Science", "SQL"],
    },
    {
        "title": "CS 188: Introduction to Artificial Intelligence",
        "instructor": "Various",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://inst.eecs.berkeley.edu/~cs188/",
        "youtube_playlist_id": "PLp8QV47qJEg7WWVg_5eOECzVPpy23UjJz",
        "level": "undergraduate",
        "year": 2023,
        "semester": "Spring",
        "subjects": ["Artificial Intelligence", "Computer Science"],
    },
    {
        "title": "CS 189/289A: Introduction to Machine Learning",
        "instructor": "Jonathan Shewchuk",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://people.eecs.berkeley.edu/~jrs/189/",
        "youtube_playlist_id": "PLCuQm2FL98HTlRmlwMk2AuFEM9n1c06HE",
        "level": "undergraduate",
        "year": 2022,
        "semester": "Spring",
        "subjects": ["Machine Learning", "Computer Science"],
    },
    {
        "title": "CS 195: Social Implications of Computer Technology",
        "instructor": "Various",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://inst.eecs.berkeley.edu/~cs195/",
        "youtube_playlist_id": "PLkFD6_40KJIybLLKl3NqsZUVMFxYq4JO3",
        "level": "undergraduate",
        "year": 2021,
        "semester": "Fall",
        "subjects": ["Ethics", "Technology and Society", "Computer Science"],
    },
    {
        "title": "CS 198-126: Modern Computer Vision",
        "instructor": "Various",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://www.youtube.com/playlist?list=PLzWRmD0Vi2KVsrCqA4VnztE4t71KnTnP5",
        "youtube_playlist_id": "PLzWRmD0Vi2KVsrCqA4VnztE4t71KnTnP5",
        "level": "undergraduate",
        "year": 2022,
        "semester": "Fall",
        "subjects": ["Computer Vision", "Deep Learning", "Machine Learning"],
    },
    {
        "title": "CS 267: Applications of Parallel Computers",
        "instructor": "James Demmel",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://sites.google.com/lbl.gov/cs267-spr2018/",
        "youtube_playlist_id": "PLkFD6_40KJIx8lWWbE-Uk069aZ1R-W-VU",
        "level": "graduate",
        "year": 2018,
        "semester": "Spring",
        "subjects": ["Parallel Computing", "High Performance Computing", "Computer Science"],
    },
    {
        "title": "CS 270: Combinatorial Algorithms and Data Structures",
        "instructor": "Prasad Raghavendra",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://people.eecs.berkeley.edu/~prasad/spring2021.html",
        "youtube_playlist_id": "PLfkeJ2f4i0AfWApBP8X8YvQfN4WbRQTC3",
        "level": "graduate",
        "year": 2021,
        "semester": "Spring",
        "subjects": ["Algorithms", "Data Structures", "Computer Science"],
    },
    {
        "title": "CS 285: Deep Reinforcement Learning",
        "instructor": "Sergey Levine",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "http://rail.eecs.berkeley.edu/deeprlcourse/",
        "youtube_playlist_id": "PL_iWQOsE6TfVYGEGiAf6h9tnVMsKX5dAX",
        "level": "graduate",
        "year": 2022,
        "semester": "Fall",
        "subjects": ["Reinforcement Learning", "Deep Learning", "Machine Learning"],
    },
    {
        "title": "CS 287: Advanced Robotics",
        "instructor": "Pieter Abbeel",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://people.eecs.berkeley.edu/~pabbeel/cs287-fa19/",
        "youtube_playlist_id": "PLwRJQ4m4UJjNBPJdt8WamRAt4XKc639wF",
        "level": "graduate",
        "year": 2019,
        "semester": "Fall",
        "subjects": ["Robotics", "Machine Learning", "Computer Science"],
    },
    {
        "title": "CS 294-158: Deep Unsupervised Learning",
        "instructor": "Pieter Abbeel",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://sites.google.com/view/berkeley-cs294-158-sp24/home",
        "youtube_playlist_id": "PLwRJQ4m4UJjPiJP3691u-qWwPGVKzSlhr",
        "level": "graduate",
        "year": 2021,
        "subjects": ["Unsupervised Learning", "Generative Models", "Deep Learning"],
    },
    {
        "title": "CS 294-165: Sketching Algorithms",
        "instructor": "Jelani Nelson",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://www.sketchingbigdata.org/fall20/lec/",
        "youtube_playlist_id": "PLIygTcviGPKCdx1AVD-CAzNk5uXDu9wIA",
        "level": "graduate",
        "year": 2020,
        "semester": "Fall",
        "subjects": ["Algorithms", "Big Data", "Computer Science"],
    },
    {
        "title": "CS 194/294-196: Large Language Model Agents",
        "instructor": "Dawn Song",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://rdi.berkeley.edu/llm-agents/f24",
        "youtube_playlist_id": "PLS01nW3RtgopsNLeM936V4TNSsvvVglLc",
        "level": "graduate",
        "year": 2024,
        "semester": "Fall",
        "subjects": ["Large Language Models", "AI Agents", "Deep Learning"],
    },
    {
        "title": "CS 194/294-267: Understanding Large Language Models",
        "instructor": "Dawn Song",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://rdi.berkeley.edu/understanding-llms/s24",
        "youtube_playlist_id": "PLJ66BAXN6D8H_gRQJGjmbnS5qCWoxJNfe",
        "level": "graduate",
        "year": 2024,
        "semester": "Spring",
        "subjects": ["Large Language Models", "AI Safety", "Deep Learning"],
    },
    # ── Electrical Engineering ────────────────────────────────────────────────
    {
        "title": "EE 16A: Designing Information Devices and Systems I",
        "instructor": "Various",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://eecs16a.org/",
        "youtube_playlist_id": "PL682UO4IMem9_svw6nCsGOaDZaYSjpgcB",
        "level": "undergraduate",
        "year": 2020,
        "semester": "Summer",
        "subjects": ["Electrical Engineering", "Linear Algebra", "Signal Processing"],
    },
    {
        "title": "EECS 16B: Designing Information Devices and Systems II",
        "instructor": "Seth Sanders",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://inst.eecs.berkeley.edu/~eecs16b/",
        "youtube_playlist_id": "PL682UO4IMem_QO6og7qXyvjMUHXNI7Hqs",
        "level": "undergraduate",
        "year": 2020,
        "semester": "Fall",
        "subjects": ["Electrical Engineering", "Signal Processing", "Control Systems"],
    },
    {
        "title": "EE 120: Signals and Systems",
        "instructor": "Murat Arcak",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://inst.eecs.berkeley.edu/~ee120/",
        "youtube_playlist_id": "PLIygTcviGPKCFASN_5cR04KUST-G97bb-",
        "level": "undergraduate",
        "year": 2019,
        "semester": "Spring",
        "subjects": ["Signal Processing", "Electrical Engineering", "Systems"],
    },
    {
        "title": "EE 123: Digital Signal Processing",
        "instructor": "Avideh Zakhor",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://inst.eecs.berkeley.edu/~ee123/",
        "youtube_playlist_id": "PLIygTcviGPKAVZtXnfoe689IBTJ2lNMmi",
        "level": "undergraduate",
        "year": 2014,
        "subjects": ["Signal Processing", "Electrical Engineering", "DSP"],
    },
    {
        "title": "EE 127: Optimization Models in Engineering",
        "instructor": "Various",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://eecs127.github.io/",
        "youtube_playlist_id": "PLIygTcviGPKAgyZlPB5QU5Size4whyrf3",
        "level": "undergraduate",
        "year": 2024,
        "semester": "Spring",
        "subjects": ["Optimization", "Machine Learning", "Electrical Engineering"],
    },
    {
        "title": "EE 225B: Digital Image Processing",
        "instructor": "Avideh Zakhor",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://inst.eecs.berkeley.edu/~ee225b/",
        "youtube_playlist_id": "PLIygTcviGPKAa5Vt6T6Noo8I0VaopzXuH",
        "level": "graduate",
        "year": 2006,
        "semester": "Spring",
        "subjects": ["Image Processing", "Signal Processing", "Electrical Engineering"],
    },
    {
        "title": "EE 229: Information Theory and Coding",
        "instructor": "Various",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://inst.eecs.berkeley.edu/~ee229a/",
        "youtube_playlist_id": "PLkFD6_40KJIxnQVFQaGjVLFpTVsLNInHD",
        "level": "graduate",
        "year": 2021,
        "subjects": ["Information Theory", "Coding Theory", "Electrical Engineering"],
    },
    {
        "title": "EECS 151/251A: Introduction to Digital Design and Integrated Circuits",
        "instructor": "Various",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://inst.eecs.berkeley.edu/~eecs151/",
        "youtube_playlist_id": "PLIygTcviGPKDxxeCDskQsOOr5eBacGmJL",
        "level": "undergraduate",
        "year": 2025,
        "semester": "Fall",
        "subjects": ["Digital Design", "FPGA", "Electrical Engineering"],
    },
    # ── Data Science ──────────────────────────────────────────────────────────
    {
        "title": "Data 8: Foundations of Data Science",
        "instructor": "Various",
        "dept": "Statistics",
        "source_url": "http://data8.org/",
        "level": "undergraduate",
        "year": 2023,
        "semester": "Spring",
        "subjects": ["Data Science", "Statistics", "Python"],
    },
    {
        "title": "DATA 100: Principles and Techniques of Data Science",
        "instructor": "Various",
        "dept": "Statistics",
        "source_url": "https://ds100.org/",
        "youtube_playlist_id": "PLIygTcviGPKBzDKR72ILypzPQZ_Cz6HcH",
        "level": "undergraduate",
        "year": 2024,
        "semester": "Fall",
        "subjects": ["Data Science", "Statistics", "Machine Learning"],
    },
    {
        "title": "Data 102: Data, Inference, and Decisions",
        "instructor": "Various",
        "dept": "Statistics",
        "source_url": "https://data102.org/",
        "youtube_playlist_id": "PLIygTcviGPKAEbY32OXjmkQbD0uRhge9Y",
        "level": "undergraduate",
        "year": 2021,
        "semester": "Spring",
        "subjects": ["Statistics", "Machine Learning", "Data Science"],
    },
    {
        "title": "Info 290: Analyzing Big Data with Twitter",
        "instructor": "Various",
        "dept": "Information",
        "source_url": "http://blogs.ischool.berkeley.edu/i290-abdt-s12/",
        "youtube_playlist_id": "PLE8C1256A28C1487F",
        "level": "graduate",
        "year": 2012,
        "semester": "Spring",
        "subjects": ["Big Data", "Data Science", "Social Media Analytics"],
    },
    # ── Mathematics ───────────────────────────────────────────────────────────
    {
        "title": "Math 1A: Calculus",
        "instructor": "Various",
        "dept": "Mathematics",
        "source_url": "https://math.berkeley.edu/courses/choosing/lowerdivcourses/math1AB",
        "youtube_playlist_id": "PLF4B4E0D54029E019",
        "level": "undergraduate",
        "year": 2009,
        "subjects": ["Calculus", "Mathematics"],
    },
    {
        "title": "Math 1B: Calculus",
        "instructor": "Various",
        "dept": "Mathematics",
        "source_url": "https://math.berkeley.edu/courses/choosing/lowerdivcourses/math1AB",
        "youtube_playlist_id": "PLB9A03CA4B84B0579",
        "level": "undergraduate",
        "year": 2009,
        "subjects": ["Calculus", "Mathematics", "Integration"],
    },
    {
        "title": "Math 54: Linear Algebra and Differential Equations",
        "instructor": "Alexander Paulin",
        "dept": "Mathematics",
        "source_url": "https://math.berkeley.edu/~apaulin/54%20(Spring%202022).html",
        "youtube_playlist_id": "PLShth7hrtLHO2U1XkrI6ZgMyuPHDxRcob",
        "level": "undergraduate",
        "year": 2020,
        "semester": "Summer",
        "subjects": ["Linear Algebra", "Differential Equations", "Mathematics"],
    },
    {
        "title": "Math 55: Discrete Mathematics",
        "instructor": "Nikhil Srivastava",
        "dept": "Mathematics",
        "source_url": "https://math.berkeley.edu/~nikhil/courses/55.f21/",
        "youtube_playlist_id": "PLaVBOvvdB5ctaLM6AmkUAODhd4JhyP_zC",
        "level": "undergraduate",
        "year": 2021,
        "semester": "Fall",
        "subjects": ["Discrete Mathematics", "Combinatorics", "Mathematics"],
    },
    # ── Statistics ────────────────────────────────────────────────────────────
    {
        "title": "STAT 2.1x: Descriptive Statistics",
        "instructor": "Various",
        "dept": "Statistics",
        "source_url": "https://www.youtube.com/playlist?list=PL_Ig1a5kxu56TfFnGlRlH2YpOBWGiYsQD",
        "youtube_playlist_id": "PL_Ig1a5kxu56TfFnGlRlH2YpOBWGiYsQD",
        "level": "undergraduate",
        "year": 2014,
        "subjects": ["Statistics", "Data Analysis", "Mathematics"],
    },
    {
        "title": "STAT 2.2x: Probability",
        "instructor": "Various",
        "dept": "Statistics",
        "source_url": "https://www.youtube.com/playlist?list=PL_Ig1a5kxu57qPZnHm-ie-D7vs9g7U-Cl",
        "youtube_playlist_id": "PL_Ig1a5kxu57qPZnHm-ie-D7vs9g7U-Cl",
        "level": "undergraduate",
        "year": 2014,
        "subjects": ["Probability", "Statistics", "Mathematics"],
    },
    {
        "title": "STAT 150: Stochastic Processes",
        "instructor": "Brett Kolesnik",
        "dept": "Statistics",
        "source_url": "https://www.youtube.com/playlist?list=PL682UO4IMem_H6exlt8NMfBSc0137_wlo",
        "youtube_playlist_id": "PL682UO4IMem_H6exlt8NMfBSc0137_wlo",
        "level": "undergraduate",
        "year": 2021,
        "semester": "Spring",
        "subjects": ["Stochastic Processes", "Probability", "Statistics"],
    },
    {
        "title": "STAT 243: Introduction to Statistical Computing",
        "instructor": "Various",
        "dept": "Statistics",
        "source_url": "https://www.youtube.com/playlist?list=PLIygTcviGPKCJjCMep25BtbRwehuNTd-l",
        "youtube_playlist_id": "PLIygTcviGPKCJjCMep25BtbRwehuNTd-l",
        "level": "graduate",
        "year": 2015,
        "semester": "Fall",
        "subjects": ["Statistical Computing", "R", "Statistics"],
    },
    # ── Physics ───────────────────────────────────────────────────────────────
    {
        "title": "Physics 7B: Introductory Physics",
        "instructor": "Various",
        "dept": "Physics",
        "source_url": "https://archive.org/details/UCBerkeley_Course_Physics_7B",
        "level": "undergraduate",
        "year": 2012,
        "subjects": ["Physics", "Thermodynamics", "Electromagnetism"],
    },
    {
        "title": "Physics 8A: Introductory Physics",
        "instructor": "Various",
        "dept": "Physics",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL-XXv-cvA_iA_KqH0J4XMvMBLr63fjDKY",
        "level": "undergraduate",
        "year": 2012,
        "subjects": ["Physics", "Mechanics", "Introduction"],
    },
    {
        "title": "Physics 10: Physics for Future Presidents",
        "instructor": "Richard Muller",
        "dept": "Physics",
        "source_url": "http://muller.lbl.gov/teaching/Physics10/PffP.html",
        "youtube_playlist_id": "PLF5B7F21FB98E3620",
        "level": "undergraduate",
        "year": 2009,
        "subjects": ["Physics", "Science Communication"],
    },
    # ── Astronomy ─────────────────────────────────────────────────────────────
    {
        "title": "Astronomy C12: The Planets",
        "instructor": "Various",
        "dept": "Astronomy",
        "source_url": "https://archive.org/details/astronomy-c12-001-fall2014-ucberkeley-1433dd89d4366df2b534c5e3b6b267776a67e7af",
        "level": "undergraduate",
        "year": 2014,
        "semester": "Fall",
        "subjects": ["Astronomy", "Planets", "Planetary Science"],
    },
    {
        "title": "Astronomy C13: Origins: from the Big Bang to the Emergence of Humans",
        "instructor": "Various",
        "dept": "Astronomy",
        "source_url": "https://archive.org/details/UCBerkeley_Course_Astronomy_C13",
        "level": "undergraduate",
        "year": 2012,
        "subjects": ["Astronomy", "Cosmology", "Origins of Life"],
    },
    # ── Social Sciences ───────────────────────────────────────────────────────
    {
        "title": "Sociology 1: Introduction to Sociology",
        "instructor": "Various",
        "dept": "Sociology",
        "source_url": "https://archive.org/details/UCBerkeley_Course_Sociology_1",
        "level": "undergraduate",
        "year": 2012,
        "subjects": ["Sociology", "Social Sciences"],
    },
    # ── Philosophy ────────────────────────────────────────────────────────────
    {
        "title": "Philosophy 3: The Nature of Mind",
        "instructor": "Various",
        "dept": "Philosophy",
        "source_url": "https://archive.org/details/UCBerkeley_Course_Philosophy_3",
        "level": "undergraduate",
        "year": 2012,
        "subjects": ["Philosophy", "Philosophy of Mind", "Cognitive Science"],
    },
    # ── Special Topics / Security ─────────────────────────────────────────────
    {
        "title": "Zero Knowledge Proofs",
        "instructor": "Various",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://www.youtube.com/playlist?list=PLS01nW3Rtgor_yJmQsGBZAg5XM4TSGpPs",
        "youtube_playlist_id": "PLS01nW3Rtgor_yJmQsGBZAg5XM4TSGpPs",
        "level": "graduate",
        "year": 2023,
        "subjects": ["Cryptography", "Zero Knowledge Proofs", "Blockchain"],
    },
    {
        "title": "Blockchain Fundamentals",
        "instructor": "Various",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://www.youtube.com/playlist?list=PLSONl1AVlZNU0QTGpbgEQXKHcmgYz-ddT",
        "youtube_playlist_id": "PLSONl1AVlZNU0QTGpbgEQXKHcmgYz-ddT",
        "level": "undergraduate",
        "year": 2018,
        "subjects": ["Blockchain", "Cryptocurrency", "Decentralized Systems"],
    },
    {
        "title": "Blockchain for Developers",
        "instructor": "Various",
        "dept": "Electrical Engineering and Computer Science",
        "source_url": "https://www.youtube.com/playlist?list=PLSONl1AVlZNUzp71_H1kb87PvIh8kIZU9",
        "youtube_playlist_id": "PLSONl1AVlZNUzp71_H1kb87PvIh8kIZU9",
        "level": "undergraduate",
        "year": 2018,
        "semester": "Spring",
        "subjects": ["Blockchain", "Smart Contracts", "Solidity"],
    },
    # ── Python / Data Skills ──────────────────────────────────────────────────
    {
        "title": "Python Boot Camp",
        "instructor": "Various",
        "dept": "Berkeley Institute for Data Science",
        "source_url": "https://www.youtube.com/playlist?list=PLKW2Azk23ZtSeBcvJi0JnL7PapedOvwz9",
        "youtube_playlist_id": "PLKW2Azk23ZtSeBcvJi0JnL7PapedOvwz9",
        "level": "undergraduate",
        "year": 2016,
        "semester": "Fall",
        "subjects": ["Python", "Data Science", "Programming"],
    },
    # ── Chemistry ────────────────────────────────────────────────────────────
    {
        "title": "Chemistry 1A: General Chemistry",
        "instructor": "Various",
        "dept": "Chemistry",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL22261BB8885D7B73",
        "level": "undergraduate",
        "year": 2012,
        "semester": "Fall",
        "subjects": ["Chemistry", "General Chemistry", "Science"],
    },
    {
        "title": "Chemistry 3B: Organic Chemistry",
        "instructor": "Various",
        "dept": "Chemistry",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL0F8FE030FD7FB95B",
        "level": "undergraduate",
        "year": 2006,
        "semester": "Spring",
        "subjects": ["Chemistry", "Organic Chemistry", "Science"],
    },
    # ── Biology ──────────────────────────────────────────────────────────────
    {
        "title": "Biology 1A: General Biology",
        "instructor": "Various",
        "dept": "Molecular and Cell Biology",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL4B95C1CB493BCC18",
        "level": "undergraduate",
        "year": 2012,
        "semester": "Fall",
        "subjects": ["Biology", "Cell Biology", "Science"],
    },
    {
        "title": "Biology 1B: General Biology — Ecology, Evolution, and Physiology",
        "instructor": "Various",
        "dept": "Integrative Biology",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL-XXv-cvA_iBklnV4A6ucBpazJQ88yW-Z",
        "level": "undergraduate",
        "year": 2015,
        "semester": "Spring",
        "subjects": ["Biology", "Ecology", "Evolution", "Physiology"],
    },
    {
        "title": "Integrative Biology 131: General Human Anatomy",
        "instructor": "Marian Diamond",
        "dept": "Integrative Biology",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL9A701D54E8896D0E",
        "level": "undergraduate",
        "year": 2005,
        "semester": "Fall",
        "subjects": ["Anatomy", "Biology", "Human Body", "Medicine"],
    },
    {
        "title": "MCB C148: Microbial Genomics and Genetics",
        "instructor": "Various",
        "dept": "Molecular and Cell Biology",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL59C08AE05E752758",
        "level": "undergraduate",
        "year": 2011,
        "semester": "Spring",
        "subjects": ["Microbiology", "Genomics", "Genetics", "Biology"],
    },
    {
        "title": "Plant and Microbial Biology 160: Experimental Plant Biology",
        "instructor": "Various",
        "dept": "Plant and Microbial Biology",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL2B7E0C3DBF1D43ED",
        "level": "undergraduate",
        "year": 2012,
        "semester": "Spring",
        "subjects": ["Plant Biology", "Botany", "Biology"],
    },
    # ── Economics ────────────────────────────────────────────────────────────
    {
        "title": "Economics 1: Introduction to Economics",
        "instructor": "Various",
        "dept": "Economics",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PLC44C3FE3E1FCDDAE",
        "level": "undergraduate",
        "year": 2011,
        "semester": "Fall",
        "subjects": ["Economics", "Microeconomics", "Macroeconomics"],
    },
    {
        "title": "Economics 100B: Economic Analysis — Macroeconomics",
        "instructor": "Various",
        "dept": "Economics",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL-XXv-cvA_iCFAuAPeqtJxl70DNRZZ2CK",
        "level": "undergraduate",
        "year": 2014,
        "semester": "Fall",
        "subjects": ["Macroeconomics", "Economics"],
    },
    {
        "title": "Economics C3: Introduction to Environmental Economics and Policy",
        "instructor": "Various",
        "dept": "Economics",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PLC19F90FAA0FCDBD2",
        "level": "undergraduate",
        "year": 2011,
        "semester": "Spring",
        "subjects": ["Environmental Economics", "Economics", "Environmental Policy"],
    },
    {
        "title": "Economics 113: American Economic History",
        "instructor": "Various",
        "dept": "Economics",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL-XXv-cvA_iCP_kfWTMuyCNFGtydWoKzm",
        "level": "undergraduate",
        "year": 2015,
        "semester": "Spring",
        "subjects": ["Economic History", "American History", "Economics"],
    },
    {
        "title": "Economics 119: Psychology and Economics",
        "instructor": "Various",
        "dept": "Economics",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL-XXv-cvA_iDaN-XzZu5IKzLBS778E0ar",
        "level": "undergraduate",
        "year": 2014,
        "semester": "Fall",
        "subjects": ["Behavioral Economics", "Economics", "Psychology"],
    },
    {
        "title": "Economics C110 / Political Science C135: Game Theory in the Social Sciences",
        "instructor": "Various",
        "dept": "Economics",
        "source_url": "https://archive.org/details/ucberkeley_webcast_itunesu_354823285",
        "level": "undergraduate",
        "year": 2009,
        "semester": "Fall",
        "subjects": ["Game Theory", "Economics", "Political Science"],
    },
    {
        "title": "Economics C181: International Trade",
        "instructor": "Various",
        "dept": "Economics",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL24DA6EF9F0179749",
        "level": "undergraduate",
        "year": 2010,
        "semester": "Fall",
        "subjects": ["International Trade", "Economics", "International Economics"],
    },
    # ── Psychology ───────────────────────────────────────────────────────────
    {
        "title": "Psychology 1: General Psychology",
        "instructor": "Various",
        "dept": "Psychology",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL-XXv-cvA_iAjlY3ifMHg88BTUGnLVbby",
        "level": "undergraduate",
        "year": 2015,
        "semester": "Spring",
        "subjects": ["Psychology", "Introduction", "Social Sciences"],
    },
    {
        "title": "Psychology 101: Research and Data Analysis in Psychology",
        "instructor": "Various",
        "dept": "Psychology",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PLA07B0BAB1D82C53C",
        "level": "undergraduate",
        "year": 2011,
        "semester": "Fall",
        "subjects": ["Psychology", "Research Methods", "Statistics"],
    },
    {
        "title": "Psychology 130: Social Psychology",
        "instructor": "Various",
        "dept": "Psychology",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL-XXv-cvA_iA6x_KHAUNVc8HQ-QOP2M3y",
        "level": "undergraduate",
        "year": 2013,
        "semester": "Fall",
        "subjects": ["Social Psychology", "Psychology", "Behavior"],
    },
    {
        "title": "Psychology 140: Developmental Psychology",
        "instructor": "Various",
        "dept": "Psychology",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL-XXv-cvA_iA0nkBtLaJdMCeQ4y3DEKw2",
        "level": "undergraduate",
        "year": 2015,
        "semester": "Spring",
        "subjects": ["Developmental Psychology", "Psychology", "Child Development"],
    },
    # ── History ──────────────────────────────────────────────────────────────
    {
        "title": "History 5: European Civilization from the Renaissance to the Present",
        "instructor": "Various",
        "dept": "History",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL-XXv-cvA_iDK7CMog80ikxN1jmPjoyAA",
        "level": "undergraduate",
        "year": 2014,
        "semester": "Fall",
        "subjects": ["History", "European History", "Western Civilization"],
    },
    {
        "title": "History C187: History of Information",
        "instructor": "Various",
        "dept": "History",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PLB3B128F0D579A46F",
        "level": "undergraduate",
        "year": 2011,
        "semester": "Fall",
        "subjects": ["History", "Information Technology", "Media History"],
    },
    # ── Cognitive Science ────────────────────────────────────────────────────
    {
        "title": "Cognitive Science C102: Scientific Approaches to Consciousness",
        "instructor": "Various",
        "dept": "Cognitive Science",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL045DAFD71C4386DD",
        "level": "undergraduate",
        "year": 2011,
        "semester": "Spring",
        "subjects": ["Cognitive Science", "Consciousness", "Neuroscience"],
    },
    {
        "title": "Cognitive Science C103: Cognitive Neuroscience",
        "instructor": "Various",
        "dept": "Cognitive Science",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PLB0E22D0372EE54DD",
        "level": "undergraduate",
        "year": 2011,
        "semester": "Spring",
        "subjects": ["Neuroscience", "Cognitive Science", "Brain"],
    },
    # ── Political Science ────────────────────────────────────────────────────
    {
        "title": "Political Science 179: International Relations",
        "instructor": "Various",
        "dept": "Political Science",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL0DBA90E8BC2757B0",
        "level": "undergraduate",
        "year": 2008,
        "semester": "Spring",
        "subjects": ["Political Science", "International Relations", "Global Politics"],
    },
    # ── Environmental Economics and Policy ───────────────────────────────────
    {
        "title": "Environmental Economics and Policy C1: Introduction",
        "instructor": "Various",
        "dept": "Environmental Economics and Policy",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL-XXv-cvA_iDoDi4YEjSRuViC1hIjenaF",
        "level": "undergraduate",
        "year": 2013,
        "semester": "Fall",
        "subjects": ["Environmental Economics", "Environmental Policy", "Sustainability"],
    },
    {
        "title": "Environmental Economics and Policy 145: Environmental Justice",
        "instructor": "Various",
        "dept": "Environmental Economics and Policy",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL77B377278B1C86B6",
        "level": "undergraduate",
        "year": 2012,
        "semester": "Fall",
        "subjects": ["Environmental Justice", "Environmental Policy", "Economics"],
    },
    # ── Legal Studies ─────────────────────────────────────────────────────────
    {
        "title": "Legal Studies 145: Law and Economics",
        "instructor": "Various",
        "dept": "Legal Studies",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL3D87557DA174747B",
        "level": "undergraduate",
        "year": 2012,
        "semester": "Spring",
        "subjects": ["Law", "Economics", "Legal Studies"],
    },
    {
        "title": "Legal Studies 160: Citizenship and Rights in American History",
        "instructor": "Various",
        "dept": "Legal Studies",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL948F6F317744AE5B",
        "level": "undergraduate",
        "year": 2012,
        "semester": "Spring",
        "subjects": ["Legal Studies", "American History", "Civil Rights"],
    },
    # ── Law ──────────────────────────────────────────────────────────────────
    {
        "title": "Law 271: Environmental Law and Policy",
        "instructor": "Various",
        "dept": "Law",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PLF51816806B113198",
        "level": "graduate",
        "year": 2009,
        "semester": "Fall",
        "subjects": ["Environmental Law", "Law", "Environmental Policy"],
    },
    # ── Physics (additional) ──────────────────────────────────────────────────
    {
        "title": "Physics 7A: Introductory Physics I — Mechanics",
        "instructor": "Various",
        "dept": "Physics",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL-XXv-cvA_iD07LOwJ2hUhr6JSufB-MCO",
        "level": "undergraduate",
        "year": 2014,
        "semester": "Fall",
        "subjects": ["Physics", "Mechanics", "Introduction"],
    },
    {
        "title": "Physics 112: Introduction to Statistical and Thermal Physics",
        "instructor": "Various",
        "dept": "Physics",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL4986431EE5B122D1",
        "level": "undergraduate",
        "year": 2012,
        "semester": "Spring",
        "subjects": ["Physics", "Thermodynamics", "Statistical Mechanics"],
    },
    # ── Sociology (additional) ────────────────────────────────────────────────
    {
        "title": "Sociology 150A: Social Organization",
        "instructor": "Various",
        "dept": "Sociology",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PLBFB989AB595269F6",
        "level": "undergraduate",
        "year": 2009,
        "semester": "Spring",
        "subjects": ["Sociology", "Social Organization", "Social Sciences"],
    },
    # ── Statistics (additional) ──────────────────────────────────────────────
    {
        "title": "Statistics 20: Introduction to Probability and Statistics",
        "instructor": "Various",
        "dept": "Statistics",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PLFCCED623A3AB020F",
        "level": "undergraduate",
        "year": 2010,
        "semester": "Fall",
        "subjects": ["Statistics", "Probability", "Mathematics"],
    },
    {
        "title": "Statistics 21: Introductory Probability and Statistics for Business",
        "instructor": "Various",
        "dept": "Statistics",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL10921DED3A8BFF53",
        "level": "undergraduate",
        "year": 2009,
        "semester": "Fall",
        "subjects": ["Statistics", "Probability", "Business"],
    },
    {
        "title": "Statistics 131A: Statistical Methods for Data Science",
        "instructor": "Various",
        "dept": "Statistics",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL-XXv-cvA_iDfdIg7gn1k_k3L_FZMv8VW",
        "level": "undergraduate",
        "year": 2015,
        "semester": "Spring",
        "subjects": ["Statistics", "Data Science", "Machine Learning"],
    },
    {
        "title": "Statistics 133: Concepts in Computing with Data",
        "instructor": "Various",
        "dept": "Statistics",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PL-XXv-cvA_iDsSPnMJlnhIyADGUmikoIO",
        "level": "undergraduate",
        "year": 2013,
        "semester": "Fall",
        "subjects": ["Statistics", "R Programming", "Data Analysis"],
    },
    # ── Public Health ────────────────────────────────────────────────────────
    {
        "title": "Public Health 250A: Epidemiologic Methods I",
        "instructor": "Various",
        "dept": "Public Health",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PLCEE8B752A135053E",
        "level": "graduate",
        "year": 2011,
        "semester": "Fall",
        "subjects": ["Epidemiology", "Public Health", "Statistics"],
    },
    {
        "title": "Public Health 241: Design and Analysis of Randomized Trials",
        "instructor": "Various",
        "dept": "Public Health",
        "source_url": "https://archive.org/details/ucberkeley-webcast-PLC6B83B40B8AD4EB5",
        "level": "graduate",
        "year": 2011,
        "semester": "Spring",
        "subjects": ["Epidemiology", "Clinical Trials", "Public Health", "Statistics"],
    },
]


class BerkeleyScraper(BaseScraper):
    source_key = "berkeley"
    university_name = "UC Berkeley"
    university_slug = "berkeley"
    university_website = "https://webcast.berkeley.edu"
    university_country = "US"

    async def scrape(self) -> ScraperResult:
        result = ScraperResult()
        seen_slugs: set[str] = set()

        for entry in BERKELEY_COURSES:
            slug = slugify(f"{entry['title']} berkeley")
            i = 2
            while slug in seen_slugs:
                slug = f"{slug}-{i}"
                i += 1
            seen_slugs.add(slug)

            course = ScrapedCourse(
                title=entry["title"],
                source_key=self.source_key,
                source_url=entry["source_url"],
                slug=slug,
                instructor=entry.get("instructor"),
                level=entry.get("level", "undergraduate"),
                year=entry.get("year"),
                semester=entry.get("semester"),
                has_video_lectures=True,
                youtube_playlist_id=entry.get("youtube_playlist_id"),
                university_name=self.university_name,
                university_slug=self.university_slug,
                department_name=entry.get("dept"),
                subjects=entry.get("subjects", []),
            )
            result.courses.append(course)

        logger.info("Berkeley: %d courses", len(result.courses))
        return result
